[package]
name = "my-wasm-project"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pdf-extract = "0.7.7"
wasm-bindgen = "0.2"
js-sys = "0.3.68"